var letters = [
        { arabic: "ﺍ" , beg: 'ﺍ' , mid: 'ﺎ' , end: 'ﺎ' , phonetics: "a, i, ou" , name: "'alif" , phonetics_desc : "A, I, OU français" , sound : 'اَ' } ,
        { arabic: "ﺏ" , beg: 'ﺑ' , mid: 'ﺒ' , end: 'ﺐ' , phonetics: "b" , name: "baa'" , phonetics_desc : "B français" , sound : 'بَ' } ,
        { arabic: "ﺕ" , beg: 'ﺗ' , mid: 'ﺘ' , end: 'ﺖ' , phonetics: "t" , name: "taa'" , phonetics_desc : "T français" , sound : 'تَ' } ,
        { arabic: "ﺙ" , beg: 'ﺛ' , mid: 'ﺜ' , end: 'ﺚ' , phonetics: "th" , name: "thaa'" , phonetics_desc : "S très léger en sortant la langue" , sound: 'ثَ' } ,
        { arabic: "ﺝ" , beg: 'ﺟ' , mid: 'ﺠ' , end: 'ﺞ' , phonetics: "j" , name: "jeem" , phonetics_desc : "J français" , sound: 'جَ' } ,
        { arabic: "ح" , beg: 'ﺣ' , mid: 'ﺤ' , end: 'ﺢ' , phonetics: "h" , name: "Ḥa" , phonetics_desc : "H expiré" , sound : 'حَ' } ,
        { arabic: "ﺥ" , beg: 'ﺧ' , mid: 'ﺨ' , end: 'ﺦ' , phonetics: "kh" , name: "khaa'" , phonetics_desc : "H soufflé en raclant le fond de la gorge" , sound : 'خَ' } ,
        { arabic: "د" , beg: 'ﺩ' , mid: 'ﺪ' , end: 'ﺪ' , phonetics: "d" , name: "daal" , phonetics_desc : "D français" , sound: 'دَ' } ,
        { arabic: "ذ" , beg: 'ﺫ' , mid: 'ﺬ' , end: 'ﺬ' , phonetics: "dh" , name: "dhaal" , phonetics_desc : "Th anglais" , sound: 'ذَ' } ,
        { arabic: "ر" , beg: 'ﺭ' , mid: 'ﺭ' , end: 'ﺮ' , phonetics: "r" , name: "raa'" , phonetics_desc : "R roulé" , sound: 'رَ' } ,
        { arabic: "ز" , beg: 'ﺯ' , mid: 'ﺯ' , end: 'ﺰ' , phonetics: "z" , name: "zeen" , phonetics_desc : "Z français" , sound: 'زَ' } ,
        { arabic: "س" , beg: 'ﺳ' , mid: 'ﺴ' , end: 'ﺲ' , phonetics: "s" , name: "seen" , phonetics_desc : "S français" , sound: 'سَ' } ,
        { arabic: "ش" , beg: 'ﺷ' , mid: 'ﺸ' , end: 'ﺶ' , phonetics: "sh" , name: "sheen" , phonetics_desc : "CH français" , sound: 'شُ' } ,
        { arabic: "ص" , beg: 'ﺻ' , mid: 'ﺼ' , end: 'ﺺ' , phonetics: "Ṣ" , name: "Sâd" , phonetics_desc : "S emphatisé" , sound: 'صَ' } ,
        { arabic: "ض" , beg: 'ﺿ' , mid: 'ﻀ' , end: 'ﺾ' , phonetics: "Ḍ" , name: "Dâd" , phonetics_desc : "D emphatisé" , sound: 'ضَ' } ,
        { arabic: "ط" , beg: 'ﻃ' , mid: 'ﻄ' , end: 'ﻂ' , phonetics: "Ṭ" , name: "Tâ" , phonetics_desc : "T emphatisé" , sound: 'طَ' } ,
        { arabic: "ظ" , beg: 'ﻇ' , mid: 'ﻈ' , end: 'ﻆ' , phonetics: "Ẓ" , name: "Zâ" , phonetics_desc : "Z emphatisé" , sound: 'ظَ' } ,
        { arabic: "ع" , beg: 'ﻋ' , mid: 'ﻌ' , end: 'ﻊ' , phonetics: "R" , name: "ʿayn" , phonetics_desc : "R qui vient du fond de la gorge" , sound: 'عَ' } ,
        { arabic: "غ" , beg: "ﻏ" , mid: "ﻐ" , end: "ﻎ" , phonetics: "R" , name: "Rayn" , phonetics_desc : "R qui vient du fond de la gorge mais très marqué" , sound: "غَ" } ,
        { arabic: "ف" , beg: 'ﻓ' , mid: 'ﻔ' , end: 'ﻒ' , phonetics: "f" , name: "faa'" , phonetics_desc : "F français" , sound: 'فَ' } ,
        { arabic: "ق" , beg: "ﻖ" , mid: "ﻘ" , end: "ﻗ" , phonetics: "Q" , name: "qaf" , phonetics_desc : "Q emphatisé" , sound: "قَ" } ,
        { arabic: "ك" , beg: 'ﻛ' , mid: 'ﻜ' , end: 'ﻚ' , phonetics: "k" , name: "kaaf" , phonetics_desc : "K français" , sound: 'كَ' } ,
        { arabic: "ل" , beg: 'ﻟ' , mid: 'ﻠ' , end: 'ﻞ' , phonetics: "l" , name: "laam" , phonetics_desc : "L français" , sound : 'لَ' } ,
        { arabic: "م" , beg: 'ﻣ' , mid: 'ﻤ' , end: 'ﻢ' , phonetics: "m" , name: "meem" , phonetics_desc : "M français" , sound: 'مَ' } ,
        { arabic: "ن" , beg: 'ﻧ' , mid: 'ﻨ' , end: 'ﻦ' , phonetics: "n" , name: "noon" , phonetics_desc : "N français" , sound: 'نَ' } ,
        { arabic: "ه" , beg: 'ﻫ' , mid: 'ﻬ' , end: 'ﻪ' , phonetics: "h" , name: "haa'" , phonetics_desc : "H légèrement soufflé" , sound: 'هَ' } ,
        { arabic: "و" , beg: "ﻭ" , mid: "ﻭ" , end: "ﻮ" , phonetics: "Wa" , name: "Waw" , phonetics_desc : "Prononcé Wa" , sound: "وَ" } ,
        { arabic: "ﻱ" , beg: "ﻳ" , mid: "ﻴ" , end: "ﻲ" , phonetics: "Ya" , name: "Ya" , phonetics_desc : "Prononcé Ya" , sound: "يَ" }
];
